### ISSUE TITLE
Compiler warning

### ISSUE THREAD

**Issue by minghia** [adalinbv/aax#3]
When I compiled the latest git pull I got the following warning:
`[  7%] Building C object CMakeFiles/AAXOBJ_LIB.dir/src/software/cpu/arch2d_sse2.c.o
/home/avasile/src/aax/src/software/cpu/arch2d_sse2.c: In function ‘_aax_generate_waveform_sse2’:
/home/avasile/src/aax/src/software/cpu/arch2d_sse2.c:92:73: warning: ‘h’ may be used uninitialized in this function [-Wmaybe-uninitialized]
       ngain = _mm_and_ps(_mm_cmplt_ps(two, nfreq), _mm_load_ps(harmonics+h));`

Looking at the code the value h is never assigned a value. So the function '_aax_generate_waveform_sse2' may give incorrect results.

**Comment by minghia** [comment]
I ran cppcheck on the src tree and got the following unitialised values:

`[src/aax_audioframe.c:1737]: (error) Uninitialized variable: mtx641
[src/aax_buffer.c:1039]: (error) Uninitialized variable: no_samples
[src/aax_buffer.c:1043]: (error) Uninitialized variable: no_samples
[src/aax_effects.c:288]: (error) Uninitialized variable: v
[src/backends/oss/device.c:507]: (error) Uninitialized struct member: info.frags
ize
[src/backends/oss/device.c:509]: (error) Uninitialized struct member: info.frags
ize
[src/software/cpu/rbuf_effects.c:320]: (error) Uninitialized variable: offs`

Some maybe false positives.

**Comment by adalinbv** [comment]
Thanks for the report,

This is quite new code so there might be some quirks like this pending. 
I'm surprised my compiler didn't throw a warning.

Anyhow, I'll fix it. Thanks!

Erik

**Comment by adalinbv** [comment]
I do think there are some false positives but I'll check them all just 
to be sure.

Erik

**Comment by adalinbv** [comment]
I've checked all of them and none of them was a real problem. But I've 
added a few initializations just to get rid of the warnings.

Erik
